import { defineConfig } from 'vite-plus';

export default defineConfig({
	defaultPackage: './apps/frontend',
	resolve: {
		tsconfigPaths: true,
	},
	test: {
		environment: 'jsdom',
		include: ['apps/frontend/src/**/*.test.{ts,tsx}'],
		exclude: ['e2e/**', '**/node_modules/**'],
	},
	fmt: {
		useTabs: true,
		tabWidth: 2,
		printWidth: 120,
		singleQuote: true,
		semi: true,
		trailingComma: 'all',
		bracketSpacing: true,
		ignorePatterns: [
			'**/node_modules/**',
			'**/dist/**',
			'**/.output/**',
			'**/.nitro/**',
			'**/.sanity/**',
			'**/.turbo/**',
			'**/.vercel/**',
			'**/build/**',
			'**/playwright-report/**',
			'**/test-results/**',
			'**/public/**',
			'**/*.svg',
			'**/*.min.js',
			'**/*.min.css',
			'package-lock.json',
			'apps/frontend/src/routeTree.gen.ts',
			'packages/shared/src/types/sanity.types.ts',
		],
	},
	lint: {
		jsPlugins: [{ name: 'vite-plus', specifier: 'vite-plus/oxlint-plugin' }],
		plugins: ['typescript', 'react', 'unicorn', 'jsx-a11y', 'import'],
		ignorePatterns: [
			'**/node_modules/**',
			'**/dist/**',
			'**/.output/**',
			'**/.nitro/**',
			'**/.sanity/**',
			'**/.turbo/**',
			'**/.vercel/**',
			'**/build/**',
			'**/playwright-report/**',
			'**/test-results/**',
			'**/public/**',
			'**/*.svg',
			'**/*.min.js',
			'**/*.min.css',
			'apps/frontend/src/routeTree.gen.ts',
			'packages/shared/src/types/sanity.types.ts',
		],
		rules: {
			'vite-plus/prefer-vite-plus-imports': 'error',
			'typescript/no-unused-vars': 'warn',
			'typescript/consistent-type-imports': 'error',
			'typescript/no-explicit-any': 'warn',
			'typescript/no-non-null-assertion': 'warn',
			'react-hooks/rules-of-hooks': 'error',
			'react-hooks/exhaustive-deps': 'warn',
			'react/jsx-no-useless-fragment': 'warn',
			'react/button-has-type': 'warn',
			'jsx-a11y/click-events-have-key-events': 'warn',
			'unicorn/no-array-for-each': 'warn',
		},
		options: {
			typeAware: true,
			typeCheck: true,
		},
	},
});
