// Export shared types that can be used across frontend and studio
export interface SanityDocument {
  _id: string;
  _type: string;
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
}

// Export generated Sanity types from studio
// These files are auto-generated by running `npm run generate-types` in the studio package
export * from './sanity.types';
export * from './sanityTypeLiterals';

// Add more shared types here as needed
