export enum sanityTypeLiterals {
  span = 'span',
  link = 'link',
  phoneNumberLink = 'phoneNumberLink',
  block = 'block',
  reference = 'reference',
  image = 'image',
  accordion = 'accordion',
  post = 'post',
  author = 'author',
  category = 'category',
  seo = 'seo',
  home = 'home',
  sanity_imagePaletteSwatch = 'sanity.imagePaletteSwatch',
  sanity_imagePalette = 'sanity.imagePalette',
  sanity_imageDimensions = 'sanity.imageDimensions',
  sanity_imageHotspot = 'sanity.imageHotspot',
  sanity_imageCrop = 'sanity.imageCrop',
  sanity_fileAsset = 'sanity.fileAsset',
  sanity_imageAsset = 'sanity.imageAsset',
  sanity_imageMetadata = 'sanity.imageMetadata',
  geopoint = 'geopoint',
  slug = 'slug',
  sanity_assetSourceData = 'sanity.assetSourceData',
}
